(defun my-color-theme ()
  "Color theme by mueki, created 2007-11-11."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "DarkSlateGray")
      (background-mode . dark)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "Cyan")
      (foreground-color . "White")
      (mouse-color . "gold")
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((action-lock-face . action-lock-face)
      (cscope-use-face . t)
      (goto-address-mail-face . message-header-to-face)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . info-xref)
      (goto-address-url-mouse-face . highlight)
      (howm-menu-key-face . howm-menu-key-face)
      (howm-menu-list-face . howm-menu-list-face)
      (howm-mode-keyword-face . howm-mode-keyword-face)
      (howm-mode-ref-face . howm-mode-ref-face)
      (howm-mode-title-face . howm-mode-title-face)
      (howm-mode-wiki-face . howm-mode-wiki-face)
      (howm-reminder-deadline-face . howm-reminder-deadline-face)
      (howm-reminder-defer-face . howm-reminder-defer-face)
      (howm-reminder-done-face . howm-reminder-done-face)
      (howm-reminder-normal-face . howm-reminder-normal-face)
      (howm-reminder-schedule-face . howm-reminder-schedule-face)
      (howm-reminder-today-face . howm-reminder-today-face)
      (howm-reminder-todo-face . howm-reminder-todo-face)
      (howm-reminder-tomorrow-face . howm-reminder-tomorrow-face)
      (howm-view-empty-face . howm-view-empty-face)
      (howm-view-hilit-face . howm-view-hilit-face)
      (howm-view-name-face . howm-view-name-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (migemo-message-prefix-face . highlight)
      (rmail-highlight-face . rmail-highlight)
      (view-highlight-face . highlight))
    (default ((t (:background "DarkSlateGray" :foreground "White"))))
    (action-lock-face ((t (nil))))
    (bbdb-company ((t (nil))))
    (bbdb-field-name ((t (:bold (bold extra-bold ultra-bold)))))
    (bbdb-field-value ((t (nil))))
    (bbdb-name ((t (:underline t))))
    (blank-space-face ((t (nil))))
    (blank-tab-face ((t (nil))))
    (blue ((t (nil))))
    (bold ((t (:bold (bold extra-bold ultra-bold) :foreground "Wheat"))))
    (bold-italic ((t (:italic (italic oblique) :bold (bold extra-bold ultra-bold) :foreground "wheat"))))
    (border ((t (:background "black"))))
    (border-glyph ((t (nil))))
    (buffer-menu-buffer ((t (:bold (bold extra-bold ultra-bold)))))
    (button ((t (:underline t))))
    (calendar-today-face ((t (:underline t :foreground "white"))))
    (comint-input-face ((t (:foreground "deepskyblue"))))
    (completions-common-part ((t (nil))))
    (completions-first-difference ((t (nil))))
    (cperl-array-face ((t (:foreground "Yellow"))))
    (cperl-hash-face ((t (:foreground "White"))))
    (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
    (cscope-file-face ((t (:foreground "yellow"))))
    (cscope-function-face ((t (:foreground "cyan"))))
    (cscope-line-face ((t (:foreground "green"))))
    (cscope-line-number-face ((t (:foreground "red"))))
    (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
    (cursor ((t (:background "Cyan"))))
    (custom-button-face ((t (nil))))
    (custom-changed-face ((t (:background "blue" :foreground "white"))))
    (custom-documentation-face ((t (nil))))
    (custom-face-tag-face ((t (:underline t))))
    (custom-group-tag-face ((t (:underline t))))
    (custom-group-tag-face-1 ((t (:underline t))))
    (custom-invalid-face ((t (:background "red" :foreground "white"))))
    (custom-modified-face ((t (:background "blue" :foreground "white"))))
    (custom-rogue-face ((t (:background "black" :foreground "pink"))))
    (custom-saved-face ((t (:underline t))))
    (custom-set-face ((t (:background "white" :foreground "blue"))))
    (custom-state-face ((t (nil))))
    (custom-variable-button-face ((t (:underline t :bold (bold extra-bold ultra-bold)))))
    (custom-variable-tag-face ((t (:underline t))))
    (cvs-filename-face ((t (:foreground "blue4"))))
    (cvs-handled-face ((t (:foreground "pink"))))
    (cvs-header-face ((t (:bold (bold extra-bold ultra-bold) :foreground "blue4"))))
    (cvs-marked-face ((t (:bold (bold extra-bold ultra-bold) :foreground "green3"))))
    (cvs-msg-face ((t (nil))))
    (cvs-need-action-face ((t (:foreground "orange"))))
    (cvs-unknown-face ((t (:foreground "red"))))
    (diary-face ((t (:foreground "red"))))
    (dired-directory ((t (:foreground "cyan"))))
    (dired-face-boring ((t (:foreground "Gray65"))))
    (dired-face-directory ((t (:bold (bold extra-bold ultra-bold) :foreground "sky blue"))))
    (dired-face-executable ((t (:foreground "green yellow"))))
    (dired-face-flagged ((t (:foreground "tomato"))))
    (dired-face-marked ((t (:foreground "light salmon"))))
    (dired-face-permissions ((t (:foreground "aquamarine"))))
    (dired-face-setuid ((t (:foreground "Red"))))
    (dired-face-socket ((t (:foreground "magenta"))))
    (dired-face-symlink ((t (:foreground "grey95"))))
    (dired-flagged ((t (nil))))
    (dired-header ((t (nil))))
    (dired-ignored ((t (nil))))
    (dired-mark ((t (nil))))
    (dired-marked ((t (nil))))
    (dired-symlink ((t (nil))))
    (dired-warning ((t (nil))))
    (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
    (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
    (display-time-time-balloon-face ((t (:foreground "red"))))
    (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
    (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
    (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
    (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
    (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
    (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
    (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
    (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
    (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
    (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
    (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
    (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
    (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
    (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
    (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
    (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
    (elscreen-tab-background-face ((t (:background "Gray50"))))
    (elscreen-tab-control-face ((t (:background "white" :foreground "black"))))
    (elscreen-tab-current-screen-face ((t (:background "white" :foreground "black"))))
    (elscreen-tab-other-screen-face ((t (:background "Gray85" :foreground "Gray50"))))
    (erc-action-face ((t (:bold (bold extra-bold ultra-bold)))))
    (erc-bold-face ((t (:bold (bold extra-bold ultra-bold)))))
    (erc-default-face ((t (nil))))
    (erc-direct-msg-face ((t (:foreground "LightSalmon"))))
    (erc-error-face ((t (:bold (bold extra-bold ultra-bold) :foreground "IndianRed"))))
    (erc-input-face ((t (:foreground "Beige"))))
    (erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
    (erc-notice-face ((t (:foreground "MediumAquamarine"))))
    (erc-pal-face ((t (:foreground "pale green"))))
    (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
    (erc-underline-face ((t (:underline t))))
    (escape-glyph ((t (:foreground "cyan"))))
    (eshell-ls-archive-face ((t (:bold (bold extra-bold ultra-bold) :foreground "IndianRed"))))
    (eshell-ls-backup-face ((t (:foreground "Grey"))))
    (eshell-ls-clutter-face ((t (:bold (bold extra-bold ultra-bold) :foreground "DimGray"))))
    (eshell-ls-directory-face ((t (:bold (bold extra-bold ultra-bold) :foreground "MediumSlateBlue"))))
    (eshell-ls-executable-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Coral"))))
    (eshell-ls-missing-face ((t (:bold (bold extra-bold ultra-bold) :foreground "black"))))
    (eshell-ls-picture-face ((t (:foreground "Violet"))))
    (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
    (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
    (eshell-ls-special-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Gold"))))
    (eshell-ls-symlink-face ((t (:bold (bold extra-bold ultra-bold) :foreground "White"))))
    (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
    (eshell-ls-todo-face ((t (:bold (bold extra-bold ultra-bold) :foreground "aquamarine"))))
    (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
    (eshell-prompt-face ((t (:foreground "powder blue"))))
    (eshell-test-failed-face ((t (:bold (bold extra-bold ultra-bold) :foreground "OrangeRed"))))
    (eshell-test-ok-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Green"))))
    (excerpt ((t (:italic (italic oblique)))))
    (ff-paths-non-existant-file-face ((t (:bold (bold extra-bold ultra-bold) :foreground "NavyBlue"))))
    (fg:black ((t (:foreground "black"))))
    (file-name-shadow ((t (nil))))
    (fixed ((t (:bold (bold extra-bold ultra-bold)))))
    (fixed-pitch ((t (nil))))
    (flyspell-duplicate-face ((t (:underline t :bold (bold extra-bold ultra-bold) :foreground "Gold3"))))
    (flyspell-incorrect-face ((t (:underline t :bold (bold extra-bold ultra-bold) :foreground "OrangeRed"))))
    (font-latex-bold-face ((t (:bold (bold extra-bold ultra-bold) :foreground "OliveDrab"))))
    (font-latex-italic-face ((t (:italic (italic oblique) :foreground "OliveDrab"))))
    (font-latex-math-face ((t (:foreground "burlywood"))))
    (font-latex-sedate-face ((t (:foreground "LightGray"))))
    (font-latex-string-face ((t (:foreground "LightSalmon"))))
    (font-latex-warning-face ((t (:foreground "Pink"))))
    (font-lock-builtin-face ((t (:bold (bold extra-bold ultra-bold) :foreground "cyan"))))
    (font-lock-comment-delimiter-face ((t (nil))))
    (font-lock-comment-face ((t (:foreground "Gold"))))
    (font-lock-constant-face ((t (:bold (bold extra-bold ultra-bold) :foreground "LightSteelBlue"))))
    (font-lock-doc-face ((t (nil))))
    (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
    (font-lock-exit-face ((t (nil))))
    (font-lock-function-name-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Yellow"))))
    (font-lock-keyword-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Cyan"))))
    (font-lock-negation-char-face ((t (nil))))
    (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
    (font-lock-reference-face ((t (:foreground "pale green"))))
    (font-lock-regexp-grouping-backslash ((t (nil))))
    (font-lock-regexp-grouping-construct ((t (nil))))
    (font-lock-string-face ((t (:foreground "Khaki"))))
    (font-lock-type-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Cyan"))))
    (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
    (font-lock-warning-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Pink"))))
    (fringe ((t (:background "darkslategrey"))))
    (gnus-cite-attribution-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Wheat"))))
    (gnus-cite-face-1 ((t (:foreground "wheat"))))
    (gnus-cite-face-10 ((t (:foreground "wheat"))))
    (gnus-cite-face-11 ((t (:foreground "turquoise"))))
    (gnus-cite-face-2 ((t (:foreground "cyan"))))
    (gnus-cite-face-3 ((t (:foreground "light yellow"))))
    (gnus-cite-face-4 ((t (:foreground "light pink"))))
    (gnus-cite-face-5 ((t (:foreground "pale green"))))
    (gnus-cite-face-6 ((t (:foreground "beige"))))
    (gnus-cite-face-7 ((t (:foreground "orange"))))
    (gnus-cite-face-8 ((t (:foreground "magenta"))))
    (gnus-cite-face-9 ((t (:foreground "violet"))))
    (gnus-emphasis-bold ((t (:bold (bold extra-bold ultra-bold) :foreground "wheat"))))
    (gnus-emphasis-bold-italic ((t (:italic (italic oblique) :bold (bold extra-bold ultra-bold)))))
    (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
    (gnus-emphasis-italic ((t (:italic (italic oblique) :foreground "white"))))
    (gnus-emphasis-underline ((t (:underline t :foreground "white"))))
    (gnus-emphasis-underline-bold ((t (:underline t :bold (bold extra-bold ultra-bold) :foreground "wheat"))))
    (gnus-emphasis-underline-bold-italic ((t (:underline t :italic (italic oblique) :bold (bold extra-bold ultra-bold)))))
    (gnus-emphasis-underline-italic ((t (:underline t :italic (italic oblique) :foreground "white"))))
    (gnus-filterhist-face-1 ((t (nil))))
    (gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))))
    (gnus-group-mail-1-face ((t (:bold (bold extra-bold ultra-bold) :foreground "aquamarine1"))))
    (gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
    (gnus-group-mail-2-face ((t (:bold (bold extra-bold ultra-bold) :foreground "aquamarine2"))))
    (gnus-group-mail-3-empty-face ((t (:foreground "Salmon"))))
    (gnus-group-mail-3-face ((t (:bold (bold extra-bold ultra-bold) :foreground "gold"))))
    (gnus-group-mail-low-empty-face ((t (:foreground "Wheat"))))
    (gnus-group-mail-low-face ((t (:bold (bold extra-bold ultra-bold) :foreground "aquamarine4"))))
    (gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))))
    (gnus-group-news-1-face ((t (:bold (bold extra-bold ultra-bold) :foreground "PaleTurquoise"))))
    (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
    (gnus-group-news-2-face ((t (:bold (bold extra-bold ultra-bold) :foreground "turquoise"))))
    (gnus-group-news-3-empty-face ((t (nil))))
    (gnus-group-news-3-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Wheat"))))
    (gnus-group-news-4-empty-face ((t (nil))))
    (gnus-group-news-4-face ((t (:bold (bold extra-bold ultra-bold)))))
    (gnus-group-news-5-empty-face ((t (nil))))
    (gnus-group-news-5-face ((t (:bold (bold extra-bold ultra-bold)))))
    (gnus-group-news-6-empty-face ((t (nil))))
    (gnus-group-news-6-face ((t (:bold (bold extra-bold ultra-bold)))))
    (gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
    (gnus-group-news-low-face ((t (:bold (bold extra-bold ultra-bold) :foreground "DarkTurquoise"))))
    (gnus-header-content-face ((t (:italic (italic oblique) :foreground "Wheat"))))
    (gnus-header-from-face ((t (:foreground "light yellow"))))
    (gnus-header-name-face ((t (:foreground "cyan"))))
    (gnus-header-newsgroups-face ((t (:italic (italic oblique) :foreground "yellow"))))
    (gnus-header-subject-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Gold"))))
    (gnus-picons-face ((t (:background "white" :foreground "black"))))
    (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
    (gnus-signature-face ((t (:italic (italic oblique) :foreground "wheat"))))
    (gnus-splash ((t (nil))))
    (gnus-splash-face ((t (:foreground "orange"))))
    (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
    (gnus-summary-high-ancient-face ((t (:bold (bold extra-bold ultra-bold) :foreground "SkyBlue"))))
    (gnus-summary-high-read-face ((t (:bold (bold extra-bold ultra-bold) :foreground "PaleGreen"))))
    (gnus-summary-high-ticked-face ((t (:bold (bold extra-bold ultra-bold) :foreground "pink"))))
    (gnus-summary-high-unread-face ((t (:bold (bold extra-bold ultra-bold) :foreground "gold"))))
    (gnus-summary-low-ancient-face ((t (:italic (italic oblique) :foreground "SkyBlue"))))
    (gnus-summary-low-read-face ((t (:italic (italic oblique) :foreground "PaleGreen"))))
    (gnus-summary-low-ticked-face ((t (:italic (italic oblique) :foreground "pink"))))
    (gnus-summary-low-unread-face ((t (:italic (italic oblique)))))
    (gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
    (gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
    (gnus-summary-normal-ticked-face ((t (:foreground "pink"))))
    (gnus-summary-normal-unread-face ((t (:foreground "wheat"))))
    (gnus-summary-selected-face ((t (:underline t :foreground "white"))))
    (gnus-x-face ((t (:background "white" :foreground "black"))))
    (green ((t (nil))))
    (gui-button-face ((t (:background "grey75"))))
    (gui-element ((t (:background "Gray80"))))
    (header-line ((t (:background "grey20" :foreground "grey90"))))
    (help-argument-name ((t (nil))))
    (highlight ((t (:background "Blue" :foreground "white"))))
    (highlight-changes-delete-face ((t (:underline t :foreground "red"))))
    (highlight-changes-face ((t (:foreground "red"))))
    (highline-face ((t (:background "black" :foreground "white"))))
    (holiday-face ((t (:background "pink" :foreground "white"))))
    (howm-menu-key-face ((t (:foreground "orange"))))
    (howm-menu-list-face ((t (nil))))
    (howm-mode-keyword-face ((t (:background "blue" :foreground "white"))))
    (howm-mode-ref-face ((t (:foreground "cyan"))))
    (howm-mode-title-face ((t (:foreground "RoyalBlue"))))
    (howm-mode-wiki-face ((t (:foreground "cyan"))))
    (howm-reminder-deadline-face ((t (:foreground "red"))))
    (howm-reminder-defer-face ((t (:foreground "magenta"))))
    (howm-reminder-done-face ((t (:foreground "gray"))))
    (howm-reminder-normal-face ((t (:foreground "blue"))))
    (howm-reminder-schedule-face ((t (:foreground "green"))))
    (howm-reminder-today-face ((t (:background "orange" :foreground "black"))))
    (howm-reminder-todo-face ((t (:foreground "yellow"))))
    (howm-reminder-tomorrow-face ((t (:background "pink" :foreground "black"))))
    (howm-view-empty-face ((t (:background "midnight blue"))))
    (howm-view-hilit-face ((t (:foreground "red"))))
    (howm-view-name-face ((t (:background "blue" :foreground "white"))))
    (html-helper-italic-face ((t (nil))))
    (info-menu-5 ((t (:underline t))))
    (info-node ((t (:italic (italic oblique) :bold (bold extra-bold ultra-bold) :foreground "white"))))
    (info-xref ((t (:bold (bold extra-bold ultra-bold) :foreground "wheat"))))
    (isearch ((t (:background "sea green"))))
    (isearch-secondary ((t (:foreground "red3"))))
    (italic ((t (:italic (italic oblique) :foreground "white"))))
    (lazy-highlight ((t (:background "paleturquoise4"))))
    (lazy-highlight-face ((t (:bold (bold extra-bold ultra-bold) :foreground "dark magenta"))))
    (left-margin ((t (nil))))
    (linemenu-face ((t (nil))))
    (link ((t (:underline t :foreground "cyan1"))))
    (link-visited ((t (:foreground "violet"))))
    (list-mode-item-selected ((t (nil))))
    (makefile-space-face ((t (:background "hotpink"))))
    (match ((t (:background "RoyalBlue3"))))
    (menu ((t (nil))))
    (message-cited-text-face ((t (:foreground "green"))))
    (message-header-cc-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Aquamarine"))))
    (message-header-name-face ((t (:foreground "Gold"))))
    (message-header-newsgroups-face ((t (:italic (italic oblique) :bold (bold extra-bold ultra-bold) :foreground "yellow"))))
    (message-header-other-face ((t (:foreground "lightGray"))))
    (message-header-subject-face ((t (:foreground "Yellow"))))
    (message-header-to-face ((t (:bold (bold extra-bold ultra-bold) :foreground "green2"))))
    (message-header-xheader-face ((t (:foreground "blue"))))
    (message-mml-face ((t (:bold (bold extra-bold ultra-bold) :foreground "khaki"))))
    (message-separator-face ((t (:background "aquamarine" :foreground "black"))))
    (minibuffer-prompt ((t (:foreground "cyan"))))
    (moccur-current-line-face ((t (:underline t))))
    (moccur-edit-done-face ((t (:bold (bold extra-bold ultra-bold) :foreground "gray30"))))
    (moccur-edit-face ((t (:bold (bold extra-bold ultra-bold) :background "Pink" :foreground "Black"))))
    (moccur-edit-file-face ((t (:bold (bold extra-bold ultra-bold) :background "gray30"))))
    (moccur-edit-reject-face ((t (:bold (bold extra-bold ultra-bold) :foreground "hot pink"))))
    (moccur-face ((t (:bold (bold extra-bold ultra-bold) :background "light grey" :foreground "Black"))))
    (mode-line ((t (:background "DarkGray" :foreground "Black"))))
    (mode-line-buffer-id ((t (:background "DarkGray" :foreground "Black"))))
    (mode-line-highlight ((t (nil))))
    (mode-line-inactive ((t (:background "grey30" :foreground "grey80"))))
    (modeline-mousable ((t (:background "DarkGray" :foreground "Black"))))
    (modeline-mousable-minor-mode ((t (:background "DarkGray" :foreground "Black"))))
    (mouse ((t (:background "gold"))))
    (my-cbface ((t (:underline t :foreground "wheat"))))
    (next-error ((t (nil))))
    (nobreak-space ((t (:underline t))))
    (paren-blink-off ((t (:foreground "gray80"))))
    (paren-face-match ((t (:background "turquoise"))))
    (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
    (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
    (paren-match ((t (:background "darkseagreen2"))))
    (paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
    (paren-mismatch-face ((t (:background "DeepPink" :foreground "white"))))
    (paren-no-match-face ((t (:background "yellow" :foreground "white"))))
    (pointer ((t (nil))))
    (primary-selection ((t (:background "blue"))))
    (query-replace ((t (nil))))
    (red ((t (nil))))
    (region ((t (:background "MediumSlateBlue" :foreground "white"))))
    (right-margin ((t (nil))))
    (scroll-bar ((t (:background "grey75"))))
    (search-buffers-face ((t (:bold (bold extra-bold ultra-bold) :background "SkyBlue" :foreground "Black"))))
    (search-buffers-header-face ((t (:bold (bold extra-bold ultra-bold) :background "gray20" :foreground "azure3"))))
    (secondary-selection ((t (:background "Sienna" :foreground "white"))))
    (sgml-comment-face ((t (:foreground "dark turquoise"))))
    (sgml-doctype-face ((t (nil))))
    (sgml-end-tag-face ((t (nil))))
    (sgml-entity-face ((t (nil))))
    (sgml-ignored-face ((t (nil))))
    (sgml-ms-end-face ((t (:foreground "green"))))
    (sgml-ms-start-face ((t (:foreground "green"))))
    (sgml-pi-face ((t (:foreground "lime green"))))
    (sgml-sgml-face ((t (nil))))
    (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
    (sgml-start-tag-face ((t (nil))))
    (shadow ((t (:foreground "grey70"))))
    (shell-option-face ((t (:foreground "blue"))))
    (shell-output-2-face ((t (:foreground "darkseagreen"))))
    (shell-output-3-face ((t (:foreground "slategrey"))))
    (shell-output-face ((t (:foreground "palegreen"))))
    (shell-prompt-face ((t (:foreground "red"))))
    (show-paren-match-face ((t (:background "turquoise" :foreground "white"))))
    (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
    (speedbar-button-face ((t (:bold (bold extra-bold ultra-bold) :foreground "magenta"))))
    (speedbar-directory-face ((t (:bold (bold extra-bold ultra-bold) :foreground "orchid"))))
    (speedbar-file-face ((t (:foreground "pink"))))
    (speedbar-highlight-face ((t (:background "black"))))
    (speedbar-selected-face ((t (:underline t :foreground "cyan"))))
    (speedbar-tag-face ((t (:foreground "yellow"))))
    (swbuff-current-buffer-face ((t (:bold (bold extra-bold ultra-bold) :foreground "red"))))
    (template-message-face ((t (:bold (bold extra-bold ultra-bold)))))
    (term-black ((t (:foreground "black"))))
    (term-blackbg ((t (:background "black"))))
    (term-blue ((t (:foreground "blue"))))
    (term-bluebg ((t (:background "blue"))))
    (term-bold ((t (:bold (bold extra-bold ultra-bold)))))
    (term-cyan ((t (:foreground "cyan"))))
    (term-cyanbg ((t (:background "cyan"))))
    (term-default-bg ((t (nil))))
    (term-default-bg-inv ((t (nil))))
    (term-default-fg ((t (nil))))
    (term-default-fg-inv ((t (nil))))
    (term-green ((t (:foreground "green"))))
    (term-greenbg ((t (:background "green"))))
    (term-invisible ((t (nil))))
    (term-invisible-inv ((t (nil))))
    (term-magenta ((t (:foreground "magenta"))))
    (term-magentabg ((t (:background "magenta"))))
    (term-red ((t (:foreground "red"))))
    (term-redbg ((t (:background "red"))))
    (term-underline ((t (:underline t))))
    (term-white ((t (:foreground "white"))))
    (term-whitebg ((t (:background "white"))))
    (term-yellow ((t (:foreground "yellow"))))
    (term-yellowbg ((t (:background "yellow"))))
    (text-cursor ((t (:background "grey15" :foreground "gainsboro"))))
    (tool-bar ((t (:background "grey75" :foreground "black"))))
    (toolbar ((t (nil))))
    (tooltip ((t (:background "lightyellow" :foreground "black"))))
    (trailing-whitespace ((t (:background "red1"))))
    (underline ((t (:underline t :foreground "white"))))
    (variable-pitch ((t (nil))))
    (vc-annotate-face-0046FF ((t (nil))))
    (vcursor ((t (:underline t :background "cyan" :foreground "blue"))))
    (vertical-border ((t (nil))))
    (vertical-divider ((t (nil))))
    (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
    (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
    (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
    (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
    (vhdl-font-lock-prompt-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Red"))))
    (vhdl-font-lock-reserved-words-face ((t (:bold (bold extra-bold ultra-bold) :foreground "Orange"))))
    (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
    (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
    (vhdl-speedbar-architecture-selected-face ((t (:underline t :foreground "Blue"))))
    (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
    (vhdl-speedbar-configuration-selected-face ((t (:underline t :foreground "DarkGoldenrod"))))
    (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
    (vhdl-speedbar-entity-selected-face ((t (:underline t :foreground "ForestGreen"))))
    (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
    (vhdl-speedbar-instantiation-selected-face ((t (:underline t :foreground "Brown"))))
    (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
    (vhdl-speedbar-package-selected-face ((t (:underline t :foreground "Grey50"))))
    (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
    (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
    (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
    (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
    (viper-search-face ((t (:background "khaki" :foreground "Black"))))
    (vvb-face ((t (:background "pink" :foreground "black"))))
    (widget-button-face ((t (:bold (bold extra-bold ultra-bold) :foreground "wheat"))))
    (widget-button-pressed-face ((t (:foreground "red"))))
    (widget-documentation-face ((t (:foreground "lime green"))))
    (widget-field-face ((t (:background "dim gray" :foreground "white"))))
    (widget-inactive-face ((t (:foreground "light gray"))))
    (widget-single-line-field-face ((t (:background "dim gray" :foreground "white"))))
    (woman-bold-face ((t (:bold (bold extra-bold ultra-bold)))))
    (woman-italic-face ((t (:foreground "beige"))))
    (woman-unknown-face ((t (:foreground "LightSalmon"))))
    (xref-keyword-face ((t (:foreground "blue"))))
    (xref-list-pilot-face ((t (:foreground "navy"))))
    (xref-list-symbol-face ((t (:foreground "navy"))))
    (yellow ((t (nil))))
    (zmacs-region ((t (:background "dark cyan" :foreground "cyan")))))))
